### ISSUE TITLE
androidannotations.log file constantly grows

### ISSUE THREAD

**Issue by valbertos** [excilys/androidannotations#1345] opened 2015-03-19 14:30 UTC
Hi!

I’ve been working with this framework for a while and I've never encountered this problem before:

The "androidannotations.log" file constantly grows, 

![16](https://cloud.githubusercontent.com/assets/2614726/6732523/b78a01ca-ce4c-11e4-9185-a68165b02fed.png)

![17](https://cloud.githubusercontent.com/assets/2614726/6732529/bf2df7ec-ce4c-11e4-85c0-06292ae9fcf4.png)

and the tasks “:app:assembleDebug” never finishes and the file gets more and more heavy (3 gigas!).

![screen shot 2015-03-19 at 15 05 13](https://cloud.githubusercontent.com/assets/2614726/6732550/e3a8b4a4-ce4c-11e4-8b8f-073cbc7d5687.png)

I will go to my previous commit -before this mess happened, and see what might be causing this problem.

Any thoughts?

**Comment by WonderCsabo** [comment] 2015-03-19 14:49
This is the normal behavior. You can reduce the [verbosity](https://github.com/excilys/androidannotations/wiki/CustomizeAnnotationProcessing#loglevel) of the log file or completely [disable it](https://github.com/excilys/androidannotations/wiki/CustomizeAnnotationProcessing#logappenderfile) (since 3.3). But eventually it will go away at the first project cleaning.

**Comment by WonderCsabo** [comment] 2015-03-19 14:51
Sorry, for some reason i skipped this part

> tasks “:app:assembleDebug” never finishes

This is a problem, it seems the annotation processing made into an infinite loop. Please check your changes, we have to investigate this.

**Comment by valbertos** [comment] 2015-03-19 14:54
Ok, I will focus on finding why "tasks ':app:assembleDebug' never finishes"  ;)
Thanks!

**Comment by valbertos** [comment] 2015-03-19 16:03
I’ve found the problem: crating an static class inside an abstract class breaks the annotation processing:


	@EBean
	public abstract class WhoIsTheBug {

	    @EBean
	    public static class ImTheBug {
	        public void testMe() {
	            Log.d("hello", "hello");
	        }
	    }
	    
	}

Without enhances annotations, I will instantiate this class like this:

WhoIsTheBug.ImTheBug instance = new WhoIsTheBug.ImTheBug();
instance.testMe();

Do you know why this happens?

**Comment by WonderCsabo** [comment] 2015-03-19 16:11
Great, i can repro with Eclipse and gradle, thanks for the minimal example!

I will debug this. BTW, @yDelouis do you have any idea? I think you worked on inner classes.

**Comment by yDelouis** [comment] 2015-03-19 16:55
There is a while loop in the processor for processing enclosing class before the inner class. And the loop stops when everything is generated.
The problem is that in case of an abstract class, we doesn't generate the subclass, so we never generate the inner class subclass and the loop never stops.

To fix this, we can generate subclass for abstract classes (which has already been discussed) or prevent inner class in abstract class.

**Comment by WonderCsabo** [comment] 2015-03-19 17:03
I see, it makes sense. I do not think we should break the convention of **not** generating subclasses for abstract classes. I think we should invalidate in this case.

**Comment by WonderCsabo** [comment] 2015-03-22 16:40
@yDelouis WDYT?

**Comment by yDelouis** [comment] 2015-03-23 21:36
I agree.

**Comment by WonderCsabo** [comment] 2015-03-24 13:19
@yDelouis if you do not mind i assigned it to you as you worked on the inner classes generation.

**Comment by yDelouis** [comment] 2015-03-24 14:26
Ok.

**Comment by WonderCsabo** [comment] 2015-04-20 09:07
I take this over.

**Closed** 2015-04-25 15:46 UTC
Labels: Defect
