### ISSUE TITLE
Abstract interfering with view injection

### ISSUE THREAD

**Issue by sosite** [excilys/androidannotations#1369] opened 2015-04-17 15:26 UTC
Two years ago Zachary Moshansky's [create a topic in mailing list](https://groups.google.com/forum/#!searchin/androidannotations/parent$20fragment/androidannotations/tvb2vrPuqBI/gU8L7A3VYQ8J) and then Piwaï's answer:
> Please create an issue if you think it should be the case.

So I copy/paste it - because it'll be great to saw it in AA ;)

> I have an abstract fragment that sets its content-view using:
`@EFragment(R.layout.fragment_navigation)`

>  Then, in a subclass, I use:
`@EFragment`

> Expecting that as its parent specified a layout and the child didn't, the parents layout wouldn't be overwritten but this does not appear to be the case. 

> As when the parent uses:
> `@ViewById(R.id.navigationGrid)
	GridView navigationGrid;`

> It doesn't inject the view....
> If I simply change the subclass to
> `@EFragment(R.layout.fragment_navigation)`

> Everything works as expected.

> Is this proper behavior for any subclass that is annotated to require the layout be specified as well?

**Comment by WonderCsabo** [comment] 2015-04-17 16:45
I would stick with the current implementation. Currently you can simply override the layout from the parent if you have to just by not passing a value to the annotation. If you want to use the same layout, just simply add the value as the post says. It also helps you easily find the associated file in Android Studio (and Eclipse).
Also if we change this, we would also have to change `EActivity` and `EViewGroup` for consistency.

**Comment by WonderCsabo** [comment] 2015-04-24 15:12
No answer since a week, i close this issue. Please do not hesitate reopen if you have something to sure.

**Closed by WonderCsabo** 2015-04-24 15:12 UTC

**Comment by ened** [comment] 2015-05-31 10:37
Just ran into the same issue for `@EActivity` - this might actually be quite helpful, and given the 4.0 milestone worth to revisit?

**Comment by WonderCsabo** [comment] 2015-05-31 10:41
My problem with this feature that currently you can tell the child activity not to use the super layout by simply not adding the value in the child `@EActivity` annotation. Of course we could add a special value for this change in 4.0, but i am not sure this feature worth breaking the existing API.

**Comment by WonderCsabo** [comment] 2015-05-31 10:42
Pinging @yDelouis and @dodgex for a consensus.

**Comment by dodgex** [comment] 2015-05-31 11:02
just to ensure i understand the issue:

```java
@EActivity(R.layout.mylayout)
class Parent extends Activity {}
```
```java
@EActivity
class Child extends Parent {}
```
Parent uses the specified layout and Child not?

this is a tough issue as there are many possible use cases. i think even for 4.0 we should not break the api here. the issues that could be caused by this change could be hard to catch. 

i think we should either let the user keep the value on all child classes or provide something like `inheritLayout = true` for the annotations. while the first one is less work on our side it results in more maintenance work for the user/developer if they want to change the layout for `Parent` and all of its childs.

**Comment by ened** [comment] 2015-05-31 11:39
`inheritLayout = true` could be, imo, a good way. `inheritLayout` could also be set to `true` by default if the parent class is `abstract`?

**Comment by sosite** [comment] 2015-05-31 12:41
`inheritLayout = true` could be a good aproach imo and it can be enough. But as @ened proposes default `true` value will be awesome feature ;)
