### ISSUE TITLE
@PreferenceAnnotations with v14.PreferenceFragment

### ISSUE THREAD

**Issue by mathieudebrito** [excilys/androidannotations#1641] opened 2015-11-26 09:16 UTC
Hi guys, 

It seems that most of preference annotations (afterPreferences, prefClick, prefChange, prefByKey) does not work with PreferenceFragment v14 :

```
@org.androidannotations.annotations.PreferenceClick can only be used on an element 
that extends one of the following classes: [android.preference.PreferenceActivity, 
android.preference.PreferenceFragment, android.support.v4.preference.PreferenceFragment, 
com.github.machinarius.preferencefragment.PreferenceFragment]
```

Will it be possible to use them with v14 ?

**Comment by WonderCsabo** [comment] 2015-11-26 09:18
Duplicate of https://github.com/excilys/androidannotations/issues/1535 which is already fixed on `develop`.

**Comment by mathieudebrito** [comment] 2015-11-26 09:19
ok thx !

**Closed by WonderCsabo** 2015-11-26 09:18 UTC
