### ISSUE TITLE
Support to generate code with UTF-8 

### ISSUE THREAD

**Issue by hbsis-lucianorodrigues** [excilys/androidannotations#1774] opened 2016-05-18 11:20 UTC
I'm programming with Android Studio, using UTF-8 to Java sources, on Windows 10, and I use latin characters (á, õ etc). Example of my code:
```
    @ViewById
    TextView código;
```
...and generated code by AA v4.0.0:
 ```
    @Override
    public void onViewChanged(HasViews hasViews) {
        this.c�digo = ((TextView) hasViews.findViewById(R.id.c�digo));
    }
```

...must be:
```
    @Override
    public void onViewChanged(HasViews hasViews) {
        this.código = ((TextView) hasViews.findViewById(R.id.código));
    }
```

Thanx!

**Comment by WonderCsabo** [comment] 2016-05-18 11:21
Duplicate of already implemented issue #1746.

**Closed by WonderCsabo** 2016-05-18 11:21 UTC
