### ISSUE TITLE
Import errors when using a library project

### ISSUE THREAD

**Issue by MatthieuLemoine** [excilys/androidannotations#1447] opened 2015-06-05 09:12 UTC
Hi!

I'm using AA for a library project. It builds without any problems.
I use this library in an app using also AA. 

In my app gradle.build, i added this dependency with `compile project(':ZEPSdk')`.
In Android Studio, I don't have any import errors.

However when I build the app module, import errors are thrown by Gradle  : 

```
C:\Utilisateurs\A605152\AndroidStudioProjects\eBasketCustom\app\src\main\java\example\sips\zep\activities\LocalizedActivity.java
Error:(12, 35) error: package com.example.zep.sdk.model does not exist
Error:(14, 39) error: cannot find symbol class LocalizedFragment_
C:\Utilisateurs\A605152\AndroidStudioProjects\eBasketCustom\app\src\main\java\example\sips\zep\ui\components\StoreItemAdapter.java
Error:(10, 35) error: package com.example.zep.sdk.model does not exist
Error:(15, 52) error: cannot find symbol class ZEPStore
Error:(17, 23) error: cannot find symbol class ZEPStore
Error:(21, 80) error: cannot find symbol class ZEPStore
C:\Utilisateurs\A605152\AndroidStudioProjects\eBasketCustom\app\src\main\java\example\sips\zep\activities\SignupActivity.java
Error:(10, 39) error: cannot find symbol class SignupFragment_
C:\Utilisateurs\A605152\AndroidStudioProjects\eBasketCustom\app\src\main\java\example\sips\zep\activities\StoresActivity.java
Error:(9, 39) error: cannot find symbol class StoresFragment_
C:\Utilisateurs\A605152\AndroidStudioProjects\eBasketCustom\app\src\main\java\example\sips\zep\ui\components\StoreView.java
Error:(13, 35) error: package com.example.zep.sdk.model does not exist
Error:(40, 26) error: cannot find symbol class ZEPStore
C:\Utilisateurs\A605152\AndroidStudioProjects\eBasketCustom\app\src\main\java\example\sips\zep\utils\FontsUtils.java
Error:(15, 35) error: package com.example.zep.sdk.utils does not exist
Note: Resolve log file to C:\Utilisateurs\A605152\AndroidStudioProjects\eBasketCustom\app\build\generated\source\apt\androidannotations.log
Note: Initialize AndroidAnnotations 3.3.1 with options {androidManifestFile=C:\Utilisateurs\A605152\AndroidStudioProjects\eBasketCustom\app\build\intermediates\manifests\full\debug\AndroidManifest.xml, resourcePackageName=com.example.zep}
Note: Start processing for 15 annotations on 35 elements
Note: AndroidManifest.xml file found with specified path: C:\Utilisateurs\A605152\AndroidStudioProjects\eBasketCustom\app\build\intermediates\manifests\full\debug\AndroidManifest.xml
Warning:A class activity declared in the AndroidManifest.xml cannot be found in the compile path: [com.example.zep.sdk.services.RTService_]
Warning:A class activity declared in the AndroidManifest.xml cannot be found in the compile path: [com.example.zep.sdk.services.BLEService_]
Note: AndroidManifest.xml found: AndroidManifest [applicationPackage=com.example.zep, componentQualifiedNames=[com.example.zep.activities.SigninActivity_, com.example.zep.activities.LocalizedActivity_, com.example.zep.activities.SettingsActivity_, com.example.zep.activities.SignupActivity_, com.example.zep.activities.StoresActivity_, org.eclipse.paho.android.service.MqttService, com.radiusnetworks.ibeacon.service.IBeaconService, com.radiusnetworks.ibeacon.IBeaconIntentProcessor], permissionQualifiedNames=[android.permission.NFC, android.permission.CAMERA, android.permission.INTERNET, android.permission.ACCESS_NETWORK_STATE, android.permission.ACCESS_WIFI_STATE, android.permission.CHANGE_WIFI_STATE, android.permission.WRITE_EXTERNAL_STORAGE, android.permission.READ_EXTERNAL_STORAGE, android.permission.VIBRATE, android.permission.FLASHLIGHT, android.permission.WAKE_LOCK, android.permission.PARTIAL_WAKE_LOCK, android.permission.READ_PHONE_STATE, android.permission.BLUETOOTH, android.permission.BLUETOOTH_ADMIN], applicationClassName=null, libraryProject=false, debugabble=false, minSdkVersion=18, maxSdkVersion=-1, targetSdkVersion=22]
Note: Found project R class: com.example.zep.R
Note: Found Android class: android.R
Note: Validating elements
Note: Validating with EActivityHandler: [com.example.zep.activities.GenericActivity, com.example.zep.activities.LocalizedActivity, com.example.zep.activities.SettingsActivity, com.example.zep.activities.SigninActivity, com.example.zep.activities.SignupActivity, com.example.zep.activities.StoresActivity]
Note: Validating with EReceiverHandler: [com.example.zep.receivers.BLEReceiver, com.example.zep.receivers.RTReceiver]
Note: Validating with EFragmentHandler: [com.example.zep.ui.fragments.GenericFragment, com.example.zep.ui.fragments.LoadingFragment, com.example.zep.ui.fragments.LocalizedFragment, com.example.zep.ui.fragments.SignupFragment, com.example.zep.ui.fragments.StoresFragment, com.example.zep.ui.fragments.UserProfilePopupFragment]
Note: Validating with PrefHandler: [mPreferences, mPreferences, mPreferences, mPreferences, mPreferences, mPreferences]
C:\Utilisateurs\A605152\AndroidStudioProjects\eBasketCustom\app\src\main\java\example\sips\zep\ui\fragments\LocalizedFragment.java
Error:(29, 35) error: package com.example.zep.sdk.model does not exist
Error:(30, 41) error: package com.example.zep.sdk.preferences does not exist
Error:(32, 35) error: package com.example.zep.sdk.utils does not exist
Error:(54, 25) error: cannot find symbol class ZEPStore
Error:(56, 25) error: cannot find symbol class ZEPStore
Error:(64, 15) error: cannot find symbol class Preferences_
Warning:(64, 28) Element PrefHandler unvalidated by
C:\Utilisateurs\A605152\AndroidStudioProjects\eBasketCustom\app\src\main\java\example\sips\zep\ui\fragments\UserProfilePopupFragment.java
Error:(39, 37) error: package com.example.zep.sdk.intents does not exist
Error:(43, 41) error: package com.example.zep.sdk.preferences does not exist
Error:(44, 35) error: package com.example.zep.sdk.utils does not exist
Error:(45, 35) error: package com.example.zep.sdk.utils does not exist
Error:(46, 35) error: package com.example.zep.sdk.utils does not exist
Error:(63, 15) error: cannot find symbol class Preferences_
Warning:(63, 28) Element PrefHandler unvalidated by
Note: Validating with ViewByIdHandler: [topImage, topTitle, mLastProductAdded, mRDLogo, mMenu, mMenuButton, mUserNameEditText, mPasswordEditText, mTextView, mUserProfileImageView, mNameUnderPhotoTextView, mUserProfileNameTextView, mUserProfileAgeTextView, listView, last_name_editText, first_name_editText, age_editText, pin_editText, pin_confirm_editText, email_editText, password_editText, password_confirm_editText, mAvatarImageView, listView, mAvatarImageView, mUserNameEditText, mAgeEditText]
Note: Validating with ClickHandler: [signin(), startSigup(), editProfile(), launchStoresActivity(), changeAvatar(), validateForm(), validateStores(), changeAvatar(), saveChanges()]
Note: Validating with ResHandler: [mPasswordIMEActionLabel, error_signin, error_localized_not_member, error_pin, error_password, error_empty_field, error_email, error_picture, error_store, error_signup]
Note: Validating with FragmentArgHandler: [mMessage]
Note: Validating with RestServiceHandler: [mZEPRestAPI, restAPI, restAPI, restAPI]
C:\Utilisateurs\A605152\AndroidStudioProjects\eBasketCustom\app\src\main\java\example\sips\zep\activities\GenericActivity.java
Error:(24, 34) error: package com.example.zep.sdk.http does not exist
Error:(25, 34) error: package com.example.zep.sdk.http does not exist
Error:(26, 41) error: package com.example.zep.sdk.preferences does not exist
Error:(28, 39) error: cannot find symbol class LoadingFragment_
Error:(47, 15) error: cannot find symbol class Preferences_
Error:(59, 15) error: cannot find symbol class ZEPRestAPI_
Error:(61, 12) error: cannot find symbol class ZEPRestAPIErrorHandler
Error:(69, 12) error: cannot find symbol class ZEPRestAPI_
Warning:(47, 28) Element PrefHandler unvalidated by
Error:(58, 5) error: @org.androidannotations.annotations.rest.RestService can only be used on an element annotated with @org.androidannotations.annotations.rest.Rest
Warning:(59, 27) Element RestServiceHandler unvalidated by
C:\Utilisateurs\A605152\AndroidStudioProjects\eBasketCustom\app\src\main\java\example\sips\zep\activities\SigninActivity.java
Error:(26, 34) error: package com.example.zep.sdk.http does not exist
Error:(29, 34) error: package com.example.zep.sdk.http does not exist
Error:(30, 41) error: package com.example.zep.sdk.preferences does not exist
Error:(37, 15) error: cannot find symbol class Preferences_
Error:(52, 15) error: cannot find symbol class ZEPRestAPI_
Error:(54, 15) error: cannot find symbol class ZEPRestAPIErrorHandler
Warning:(37, 28) Element PrefHandler unvalidated by
Error:(51, 5) error: @org.androidannotations.annotations.rest.RestService can only be used on an element annotated with @org.androidannotations.annotations.rest.Rest
Warning:(52, 27) Element RestServiceHandler unvalidated by
C:\Utilisateurs\A605152\AndroidStudioProjects\eBasketCustom\app\src\main\java\example\sips\zep\ui\fragments\SignupFragment.java
Error:(17, 34) error: package com.example.zep.sdk.http does not exist
Error:(18, 34) error: package com.example.zep.sdk.http does not exist
Error:(19, 41) error: package com.example.zep.sdk.preferences does not exist
Error:(20, 35) error: package com.example.zep.sdk.utils does not exist
Error:(21, 35) error: package com.example.zep.sdk.utils does not exist
Error:(41, 37) error: cannot find symbol class LocalizedActivity_
Error:(42, 37) error: cannot find symbol class StoresActivity_
Error:(103, 15) error: cannot find symbol class ZEPRestAPI_
Error:(105, 15) error: cannot find symbol class ZEPRestAPIErrorHandler
Error:(108, 15) error: cannot find symbol class Preferences_
Warning:(108, 28) Element PrefHandler unvalidated by
Error:(102, 5) error: @org.androidannotations.annotations.rest.RestService can only be used on an element annotated with @org.androidannotations.annotations.rest.Rest
Warning:(103, 27) Element RestServiceHandler unvalidated by
C:\Utilisateurs\A605152\AndroidStudioProjects\eBasketCustom\app\src\main\java\example\sips\zep\ui\fragments\StoresFragment.java
Error:(11, 34) error: package com.example.zep.sdk.http does not exist
Error:(12, 34) error: package com.example.zep.sdk.http does not exist
Error:(13, 35) error: package com.example.zep.sdk.model does not exist
Error:(14, 41) error: package com.example.zep.sdk.preferences does not exist
Error:(44, 25) error: cannot find symbol class ZEPStore
Error:(46, 25) error: cannot find symbol class ZEPStore
Error:(51, 15) error: cannot find symbol class ZEPRestAPI_
Error:(53, 15) error: cannot find symbol class ZEPRestAPIErrorHandler
Error:(56, 15) error: cannot find symbol class Preferences_
Error:(96, 47) error: cannot find symbol class ZEPStore
Warning:(56, 28) Element PrefHandler unvalidated by
Error:(50, 5) error: @org.androidannotations.annotations.rest.RestService can only be used on an element annotated with @org.androidannotations.annotations.rest.Rest
Warning:(51, 27) Element RestServiceHandler unvalidated by
Note: Validating with ReceiverActionHandler: [onCashRegisterDetected(android.content.Context,android.content.Intent), onCashRegisterNoMoreDetected(android.content.Context,android.content.Intent), onCashRegisterNotDetected(android.content.Context,android.content.Intent), onBluetoothDisabled(android.content.Context,android.content.Intent), onPaymentStarted(android.content.Context,android.content.Intent), onPaymentDone(android.content.Context,android.content.Intent)]
Note: Validating with OnActivityResultHandler: [onResultCapture(int,android.content.Intent), onResultPhotoCropped(int,android.content.Intent), onResult(int,android.content.Intent), onResultPhotoCropped(int,android.content.Intent)]
Note: Validating with AfterInjectHandler: [afterInject(), init(), init(), init()]
Note: Validating with AfterViewsHandler: [loadFragment(), customizeActionBar(), init(), checkIfUserAlreadyConnected(), setFocusOnUsername(), customizePasswordEditText(), displayMessage(), displayUserProfile(), retrieveStoreList(), fillUserProfile()]
Note: Validating with UiThreadHandler: [displayToast(java.lang.String), failSignin(), startHome(), failSignUp(), startHome(), displayStoreList(java.util.ArrayList<ZEPStore>)]
Note: Validating with BackgroundHandler: [signinBack(com.example.ebasket.lib.pojos.ZEPUser), submit(com.example.ebasket.lib.pojos.ZEPUser), retrieveStoreList()]
Note: Processing root elements
Note: Processing root elements EActivityHandler: [com.example.zep.activities.GenericActivity, com.example.zep.activities.SigninActivity, com.example.zep.activities.SignupActivity, com.example.zep.activities.StoresActivity, com.example.zep.activities.LocalizedActivity, com.example.zep.activities.SettingsActivity]
Note: Processing root elements EReceiverHandler: [com.example.zep.receivers.BLEReceiver, com.example.zep.receivers.RTReceiver]
Note: Processing root elements EFragmentHandler: [com.example.zep.ui.fragments.SignupFragment, com.example.zep.ui.fragments.LocalizedFragment, com.example.zep.ui.fragments.LoadingFragment, com.example.zep.ui.fragments.UserProfilePopupFragment, com.example.zep.ui.fragments.GenericFragment, com.example.zep.ui.fragments.StoresFragment]
Note: Processing enclosed elements
Note: Processing enclosed elements with PrefHandler: [org.androidannotations.model.AnnotationElements$AnnotatedAndRootElements@1d95fc74, org.androidannotations.model.AnnotationElements$AnnotatedAndRootElements@f5c9eda, org.androidannotations.model.AnnotationElements$AnnotatedAndRootElements@65b61061, org.androidannotations.model.AnnotationElements$AnnotatedAndRootElements@4c667e8]
Note: Processing enclosed elements with ViewByIdHandler: [org.androidannotations.model.AnnotationElements$AnnotatedAndRootElements@2fe06481, org.androidannotations.model.AnnotationElements$AnnotatedAndRootElements@2cdbafba, org.androidannotations.model.AnnotationElements$AnnotatedAndRootElements@374aa5c9, org.androidannotations.model.AnnotationElements$AnnotatedAndRootElements@3ddb025f, org.androidannotations.model.AnnotationElements$AnnotatedAndRootElements@d49db2c, org.androidannotations.model.AnnotationElements$AnnotatedAndRootElements@8e1a0c4, org.androidannotations.model.AnnotationElements$AnnotatedAndRootElements@577c7c9a, org.androidannotations.model.AnnotationElements$AnnotatedAndRootElements@58e2fe7, org.androidannotations.model.AnnotationElements$AnnotatedAndRootElements@21372bfd, org.androidannotations.model.AnnotationElements$AnnotatedAndRootElements@5c4242c9, org.androidannotations.model.AnnotationElements$AnnotatedAndRootElements@4cad8bdd, org.androidannotations.model.AnnotationElements$AnnotatedAndRootElements@4fb491a5, org.androidannotations.model.AnnotationElements$AnnotatedAndRootElements@7e882619, org.androidannotations.model.AnnotationElements$AnnotatedAndRootElements@3652e5e3, org.androidannotations.model.AnnotationElements$AnnotatedAndRootElements@6f000a92, org.androidannotations.model.AnnotationElements$AnnotatedAndRootElements@44b2e161, org.androidannotations.model.AnnotationElements$AnnotatedAndRootElements@11b3ea27, org.androidannotations.model.AnnotationElements$AnnotatedAndRootElements@66c0ee54, org.androidannotations.model.AnnotationElements$AnnotatedAndRootElements@5fb9d8ed, org.androidannotations.model.AnnotationElements$AnnotatedAndRootElements@3662dfd7, org.androidannotations.model.AnnotationElements$AnnotatedAndRootElements@18779882, org.androidannotations.model.AnnotationElements$AnnotatedAndRootElements@c083a9f, org.androidannotations.model.AnnotationElements$AnnotatedAndRootElements@7e3cc02b, org.androidannotations.model.AnnotationElements$AnnotatedAndRootElements@7e65473f]
Note: Processing enclosed elements with RestServiceHandler: [org.androidannotations.model.AnnotationElements$AnnotatedAndRootElements@68770dd5, org.androidannotations.model.AnnotationElements$AnnotatedAndRootElements@3703bdd5, org.androidannotations.model.AnnotationElements$AnnotatedAndRootElements@68bb389d, org.androidannotations.model.AnnotationElements$AnnotatedAndRootElements@3ecc1136]
Note: Processing enclosed elements with AfterInjectHandler: [org.androidannotations.model.AnnotationElements$AnnotatedAndRootElements@1beb13d8, org.androidannotations.model.AnnotationElements$AnnotatedAndRootElements@9a4fcc1, org.androidannotations.model.AnnotationElements$AnnotatedAndRootElements@66d7157f, org.androidannotations.model.AnnotationElements$AnnotatedAndRootElements@1adb3de5]
Note: Processing enclosed elements with AfterViewsHandler: [org.androidannotations.model.AnnotationElements$AnnotatedAndRootElements@2cdcfffd, org.androidannotations.model.AnnotationElements$AnnotatedAndRootElements@59504f52, org.androidannotations.model.AnnotationElements$AnnotatedAndRootElements@78861403, org.androidannotations.model.AnnotationElements$AnnotatedAndRootElements@6b8ce77b, org.androidannotations.model.AnnotationElements$AnnotatedAndRootElements@5d2c1e75, org.androidannotations.model.AnnotationElements$AnnotatedAndRootElements@4881402d, org.androidannotations.model.AnnotationElements$AnnotatedAndRootElements@db2df0f, org.androidannotations.model.AnnotationElements$AnnotatedAndRootElements@1c0a7e65]
Note: Processing enclosed elements with UiThreadHandler: [org.androidannotations.model.AnnotationElements$AnnotatedAndRootElements@3cfc77dd, org.androidannotations.model.AnnotationElements$AnnotatedAndRootElements@61b07fe, org.androidannotations.model.AnnotationElements$AnnotatedAndRootElements@261de457, org.androidannotations.model.AnnotationElements$AnnotatedAndRootElements@4cc3cb8d]
Note: Number of files generated by AndroidAnnotations: 13
Note: Writting following API classes in project: []
Note: Generating class: com.example.zep.activities.LocalizedActivity_
Note: Generating class: com.example.zep.activities.SettingsActivity_
Note: Generating class: com.example.zep.activities.SigninActivity_
Note: Generating class: com.example.zep.activities.SignupActivity_
Note: Generating class: com.example.zep.activities.StoresActivity_
Note: Generating class: com.example.zep.ui.fragments.GenericFragment_
Note: Generating class: com.example.zep.ui.fragments.LoadingFragment_
Note: Generating class: com.example.zep.ui.fragments.LocalizedFragment_
Note: Generating class: com.example.zep.ui.fragments.SignupFragment_
Note: Generating class: com.example.zep.ui.fragments.StoresFragment_
Note: Generating class: com.example.zep.ui.fragments.UserProfilePopupFragment_
Note: Generating class: com.example.zep.receivers.BLEReceiver_
Note: Generating class: com.example.zep.receivers.RTReceiver_
Note: Time measurements: [Whole Processing = 610 ms], [Generate Sources = 477 ms], [Process Annotations = 57 ms], [Extract Annotations = 22 ms], [Validate Annotations = 21 ms], [Find R Classes = 15 ms], [Extract Manifest = 10 ms], 
Note: Finish processing
Note: Start processing for 0 annotations on 0 elements
Note: Time measurements: [Whole Processing = 1 ms], 
Note: Finish processing
12 warnings
Error:Execution failed for task ':app:compileDebugJava'.
> Compilation failed; see the compiler error output for details.
Information:BUILD FAILED
Information:Total time: 6.22 secs
Information:62 errors
Information:12 warnings
Information:See complete output in console
```

I use the 3.3.1 version of AA.

Have you ever had this kind of problem ?
Thanks for your help.

**Comment by WonderCsabo** [comment] 2015-06-05 09:16
So your library project is using AA, and the app project is also using AA?

**Comment by MatthieuLemoine** [comment] 2015-06-05 09:20
@WonderCsabo yes

**Comment by WonderCsabo** [comment] 2015-06-05 09:23
@MatthieuLemoine i never used that setup. Can i ask you to create a skeleton project that resembles your setup and reproduces the error?

**Comment by MatthieuLemoine** [comment] 2015-06-05 11:28
@WonderCsabo I made a skeleton project with 3 EBeans in a lib project and a single Activity app using EActivity annotation. When i try to inject those 3 Beans I have the same problem and the same errors : 

````
Note: Resolve log file to C:\Utilisateurs\A605152\AndroidStudioProjects\MyApplication2\app\build\generated\source\apt\androidannotations.log
Note: Initialize AndroidAnnotations 3.3.1 with options {androidManifestFile=C:\Utilisateurs\A605152\AndroidStudioProjects\MyApplication2\app\build\intermediates\manifests\full\debug\AndroidManifest.xml, resourcePackageName=a605152.example.com.myapplication}
Note: Start processing for 2 annotations on 5 elements
Note: AndroidManifest.xml file found with specified path: C:\Utilisateurs\A605152\AndroidStudioProjects\MyApplication2\app\build\intermediates\manifests\full\debug\AndroidManifest.xml
Note: AndroidManifest.xml found: AndroidManifest [applicationPackage=a605152.example.com.myapplication, componentQualifiedNames=[a605152.example.com.myapplication.MainActivity_], permissionQualifiedNames=[], applicationClassName=null, libraryProject=false, debugabble=false, minSdkVersion=18, maxSdkVersion=-1, targetSdkVersion=22]
Note: Found project R class: a605152.example.com.myapplication.R
Note: Found Android class: android.R
Note: Validating elements
Note: Validating with EActivityHandler: [a605152.example.com.myapplication.MainActivity]
Note: Validating with BeanHandler: [bean, otherBean, thirdBean]
C:\Utilisateurs\A605152\AndroidStudioProjects\MyApplication2\app\src\main\java\a605152\example\com\myapplication\MainActivity.java
Error:(7, 39) error: cannot find symbol class MyBean
Error:(8, 44) error: cannot find symbol class MyOtherBean
Error:(9, 44) error: cannot find symbol class MyThirdBean
Error:(18, 5) error: cannot find symbol class MyBean
Error:(20, 5) error: cannot find symbol class MyOtherBean
Error:(22, 5) error: cannot find symbol class MyThirdBean
Error:(17, 5) error: @org.androidannotations.annotations.Bean can only be used on an element annotated with @org.androidannotations.annotations.EBean
Warning:(18, 12) Element BeanHandler unvalidated by
Error:(19, 5) error: @org.androidannotations.annotations.Bean can only be used on an element annotated with @org.androidannotations.annotations.EBean
Warning:(20, 17) Element BeanHandler unvalidated by
Error:(21, 5) error: @org.androidannotations.annotations.Bean can only be used on an element annotated with @org.androidannotations.annotations.EBean
Warning:(22, 17) Element BeanHandler unvalidated by
Note: Processing root elements
Note: Processing root elements EActivityHandler: [a605152.example.com.myapplication.MainActivity]
Note: Processing enclosed elements
Note: Number of files generated by AndroidAnnotations: 1
Note: Writting following API classes in project: []
Note: Generating class: a605152.example.com.myapplication.MainActivity_
Note: Time measurements: [Whole Processing = 227 ms], [Generate Sources = 98 ms], [Process Annotations = 75 ms], [Find R Classes = 17 ms], [Validate Annotations = 11 ms], [Extract Manifest = 9 ms], [Extract Annotations = 2 ms], 
Note: Finish processing
Note: Start processing for 0 annotations on 0 elements
Note: Time measurements: [Whole Processing = 0 ms], 
Note: Finish processing
3 warnings
Error:Execution failed for task ':app:compileDebugJava'.
> Compilation failed; see the compiler error output for details.
````
I created a repo for this test project if you want to try : https://github.com/MatthieuLemoine/AnnotationsLibTest

**Comment by WonderCsabo** [comment] 2015-06-05 11:49
Thanks, i will try it later today and get back to you.

**Comment by dodgex** [comment] 2015-06-05 12:02
@WonderCsabo looks like the processor does not get the dependency for the library project from `compile project(':testlibrary')`.

**Comment by WonderCsabo** [comment] 2015-06-06 11:24
@MatthieuLemoine i have to say i do not know what is going on. I removed AA from the project completely, and it still cannot see `MyBean` etc from project `app`. 

After that, i even removed the Android plugin, and applied the Java plugin. That way the project compiles. Maybe this is a bug with the Android plugin. :confused:

**Comment by WonderCsabo** [comment] 2015-06-06 12:57
@MatthieuLemoine i managed to fix the project. I tried everything, and it seems i accidentally found the problem. Here is the repo: https://github.com/WonderCsabo/AnnotationsLibTest.

I do not have the time to bisect the real cause. Try to expand my project to your real project.

**Comment by WonderCsabo** [comment] 2015-06-06 12:58
BTW, this is definitely not an AA problem.

**Comment by MatthieuLemoine** [comment] 2015-06-06 16:47
@WonderCsabo Thanks! I will try it on monday.

**Comment by MatthieuLemoine** [comment] 2015-06-08 09:03
@WonderCsabo you're right it's not an AA problem but a gradle issue. I copied your gradle files back to my project and now it works like a charm. Thank you !

**Comment by WonderCsabo** [comment] 2015-06-08 09:04
Great! Did you find out the real problem? If you will, please share it with us. I am closing this issue.

**Closed by WonderCsabo** 2015-06-08 09:04 UTC

**Comment by MatthieuLemoine** [comment] 2015-06-08 14:18
I find it out ! It seems that the buildTypes block in my library build.gradle file is the cause. It builts without any errors without it.

````
    buildTypes {
        release {
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
````

**Comment by WonderCsabo** [comment] 2015-06-08 14:21
Interesting, I think I only used debug builds. However it makes sense in
release builds, proguard removed all the not used classes.

**Comment by MatthieuLemoine** [comment] 2015-06-08 14:42
@WonderCsabo It was a proguard issue after all. Sorry to have wasted your time !

**Comment by LouisCAD** [comment] 2016-06-23 12:11
@MatthieuLemoine Isn't the builtTypes snippet you showed us from a library module?
