### ISSUE TITLE
Can AA support radiogroup @checkedchange

### ISSUE THREAD

**Issue by peng8350** [excilys/androidannotations#1870] opened 2016-10-08 12:33 UTC
I want to setOnCheckChangeListener to the RadioGroup,But I find the @CheckedChange is not for the RadioGroup, Does AA have another Solution scheme?

**Comment by WonderCsabo** [comment] 2016-10-08 18:57
Duplicate of https://github.com/excilys/androidannotations/issues/1309 .

**Closed by WonderCsabo** 2016-10-08 18:57 UTC
