### ISSUE TITLE
Views are null at first @AfterViews in @PreferenceScreen @EActivity

### ISSUE THREAD

**Issue by m-radzikowski** [excilys/androidannotations#1574] opened 2015-10-02 16:55 UTC
I have very simple preference Activity:

```java
@EActivity(R.layout.a_settings)
@PreferenceScreen(R.xml.preferences)
public class SettingsActivity extends PreferenceActivity {

	@ViewById(R.id.toolbar)
	protected Toolbar toolbar;

	@PreferenceByKey(R.string.some_preference)
	protected Preference somePref;

	@AfterViews
	protected void setupToolbar() {
		toolbar.setNavigationOnClickListener(new View.OnClickListener() {
			@Override
			public void onClick(View v) {
				onBackPressed();
			}
		});
	}
```

and it causes NPE on toolbar#setNavi...

When i debugged it it turned out that `#setupToolbar()` method is in fact called 3 times and at first 2 times `toolbar` is `null`, at third time it's valid object.

Of course workaround is simple - check if used views are not null:
```java
	@AfterViews
	protected void setupToolbar() {
		if (toolbar != null) {
			toolbar.setNavigationOnClickListener(new View.OnClickListener() {
				@Override
				public void onClick(View v) {
					onBackPressed();
				}
			});
		}
	}
```

But it looks like a bug - in `@AfterViews` method all views should be always already injected, right?

**Comment by WonderCsabo** [comment] 2015-10-02 16:58
Can you share a simple project which can reproduce the issue?

**Comment by WonderCsabo** [comment] 2015-10-07 09:41
@m-radzikowski any updates on this?

**Comment by m-radzikowski** [comment] 2015-10-07 09:45
No, sorry, I will build simple example tomorrow.

**Comment by WonderCsabo** [comment] 2015-10-07 09:46
OK thanks.

**Comment by WonderCsabo** [comment] 2015-10-11 19:34
@m-radzikowski any news on this? Without a proper example project we cannot investigate this issue effectively.

**Comment by m-radzikowski** [comment] 2015-10-12 10:14
Here you go: https://github.com/m-radzikowski/AA1574-example

In logs there are always two errors before TextView is set and can be changed.

**Comment by WonderCsabo** [comment] 2015-10-12 11:07
OK, now i understand what is the problem. If you use `@PreferenceScreen(R.xml.settings)`, then you cannot add a layout in `@EActivity`, because the `PreferenceActivity` already adds its special layout to support `PreferenceScreen`. If you want to add things in the layout, you should do it in the *xml/settings.xml* file.

**Comment by m-radzikowski** [comment] 2015-10-14 07:07
Hm, setting own view for preference screen is possible in ordinary Android apps as long as it has `@android:id/list` element, as in my example.

In my example I've added simple TextView, but in my real app I've `android.support.design.widget.AppBarLayout` with `android.support.v7.widget.Toolbar` to maintain visual consistency with other views. Is setting something like that possible in `xml/settings.xml`?

But I understand what causes this issue and I assume there is no easy (or any) way to fix it. I will live with  my workaround with null check in this single place.

**Comment by WonderCsabo** [comment] 2015-10-14 07:18
Oops, i was not aware of that.

I now not just looked at your code, but actually built and ran the app. The `TextView` is correctly set! I do not know why it is `null` in your case... I am running Android 5.

**Comment by m-radzikowski** [comment] 2015-10-14 07:22
Please look in logs - there are two errors before text is successfully changed.

**Comment by WonderCsabo** [comment] 2015-10-14 07:29
That is because the PreferenceActivity calls `setContentView()` [two](http://grepcode.com/file/repository.grepcode.com/java/ext/com.google.android/android/5.1.1_r1/android/preference/PreferenceActivity.java#550) [times](http://grepcode.com/file/repository.grepcode.com/java/ext/com.google.android/android/5.1.1_r1/android/preference/PreferenceActivity.java#633) with a different layout. We cannot do anything about that. Yeah, you have to use a `null` check, of course. But the view will be injected at last.

**Comment by WonderCsabo** [comment] 2015-10-14 07:36
If it is not clear, we override `setContentView()` and inject views there. This is because if a user cannot use `layout` in `@EActivity`, then the views can be still injected that way.

**Comment by WonderCsabo** [comment] 2015-10-16 21:23
@m-radzikowski is that acceptable for you?

**Comment by m-radzikowski** [comment] 2015-10-16 21:26
Yea. Maybe it would be good to add information about it in wiki?

**Comment by WonderCsabo** [comment] 2015-10-16 21:30
Done. Thanks!

**Closed by WonderCsabo** 2015-10-16 21:30 UTC
