### ISSUE TITLE
Unexpected error while compilation with newest support-v4 library version 22.2.0

### ISSUE THREAD

**Issue by aashatunov** [excilys/androidannotations#1451] opened 2015-06-06 17:07 UTC
Stack trace:

17:42:14.373 [Daemon worker Thread 75] INFO  o.a.AndroidAnnotationProcessor:107 - Start processing for 16 annotations on 421 elements
17:42:14.650 [Daemon worker Thread 75] ERROR o.a.AndroidAnnotationProcessor:267 - Something went wrong: Unexpected error in AndroidAnnotations 3.3.1!
You should check if there is already an issue about it on https://github.com/excilys/androidannotations/search?q=com.sun.tools.javac.code.Symbol%24CompletionFailure&type=Issues
If none exists, please open a new one with the following content and tell us if you can reproduce it or not. Don't forget to give us as much information as you can (like parts of your code in failure).
Java version: javac 1.7.0_71

Stacktrace: com.sun.tools.javac.code.Symbol$CompletionFailure: class file for android.support.v4.widget.DrawerLayout$State not found

17:42:14.651 [Daemon worker Thread 75] INFO  o.a.p.TimeStats:81 - Time measurements: [Whole Processing = 279 ms], 
17:42:14.652 [Daemon worker Thread 75] INFO  o.a.AndroidAnnotationProcessor:121 - Finish processing

**Comment by WonderCsabo** [comment] 2015-06-06 17:15
Duplicate of #1435. Please read that issue for details.

**Closed by WonderCsabo** 2015-06-06 17:15 UTC
