### ISSUE TITLE
Processing crash: android.support.v4.app.DialogFragment$DialogStyle not found

### ISSUE THREAD

**Issue by matsujun** [excilys/androidannotations#1435] opened 2015-05-29 05:55 UTC
When I use support library v22.2, I got following error.
```
Stacktrace: com.sun.tools.javac.code.Symbol$CompletionFailure: android.support.v4.app.DialogFragment$DialogStyleのクラス・ファイルが見つかりません
```

```のクラス・ファイルが見つかりません``` is ```Class, File not found.```

support.v4.app.DialogFragment on v22.1 or earlier seems to have ```private @interface DialogStyle {}```
But it seems to be removed on v22.2.

**Comment by WonderCsabo** [comment] 2015-05-29 06:18
Please provide the full stack trace and the annotated code.

**Comment by savannabreeze** [comment] 2015-05-29 07:39
I've encountered the same error. Below is the stacktrace from androidannotations.log.

```
14:17:30.910 [Daemon worker Thread 17] INFO  o.a.p.TimeStats:81 - Time measurements: [Whole Processing = 106 ms], 
14:17:30.910 [Daemon worker Thread 17] INFO  o.a.AndroidAnnotationProcessor:121 - Finish processing
14:19:55.938 [Daemon worker Thread 18] INFO  o.a.AndroidAnnotationProcessor:83 - Initialize AndroidAnnotations 3.3.1 with options {androidManifestFile=/home/hirdian/Documents/GudPoinAndroid/app/build/intermediates/manifests/full/debug/AndroidManifest.xml, resourcePackageName=com.gudpoin}
14:19:55.999 [Daemon worker Thread 18] INFO  o.a.AndroidAnnotationProcessor:107 - Start processing for 24 annotations on 240 elements
14:19:56.102 [Daemon worker Thread 18] ERROR o.a.AndroidAnnotationProcessor:267 - Something went wrong: Unexpected error in AndroidAnnotations 3.3.1!
You should check if there is already an issue about it on https://github.com/excilys/androidannotations/search?q=com.sun.tools.javac.code.Symbol%24CompletionFailure&type=Issues
If none exists, please open a new one with the following content and tell us if you can reproduce it or not. Don't forget to give us as much information as you can (like parts of your code in failure).
Java version: javac 1.7.0_80
Javac processors options: androidManifestFile=/home/hirdian/Documents/GudPoinAndroid/app/build/intermediates/manifests/full/debug/AndroidManifest.xml, resourcePackageName=com.gudpoin
Stacktrace: com.sun.tools.javac.code.Symbol$CompletionFailure: class file for android.support.v4.app.DialogFragment$DialogStyle not found

14:19:56.102 [Daemon worker Thread 18] INFO  o.a.p.TimeStats:81 - Time measurements: [Whole Processing = 103 ms], 
14:19:56.102 [Daemon worker Thread 18] INFO  o.a.AndroidAnnotationProcessor:121 - Finish processing
```

I do have a class extending DialogFragment annotated, like so:
```
@EFragment(R.layout.some_layout)
public class HomeOverflowFragment extends DialogFragment{
    //Some Code
}
```
I've also tried removing the annotation in that class and the error is still there. Using appcompat-v7:22.2.0. Hope this could help.

**Comment by WonderCsabo** [comment] 2015-05-29 07:51
This is weird, because the whole stacktrace is not shown, only the message of the exception. Did you copy the whole trace?

**Comment by savannabreeze** [comment] 2015-05-29 08:34
Yep, that is the only content inside androidannotations.log after the build failed.

**Comment by matsujun** [comment] 2015-05-29 08:34
Only one line is written in log file.

**Comment by WonderCsabo** [comment] 2015-05-29 08:36
Can one of you guys create a minimal example project which can reproduce the issue?

**Comment by domsu** [comment] 2015-05-29 08:54
Same here.

In my log also:

"Note: Resolve log file to /home/dsuszczewicz/dev/repo/AndroidMenuOrder/Mordor/core/build/generated/source/apt/androidannotations.log
Note: Initialize AndroidAnnotations 3.2 with options {androidManifestFile=/home/dsuszczewicz/dev/repo/AndroidMenuOrder/Mordor/core/build/intermediates/bundles/release/aapt/AndroidManifest.xml}
Warning:The following options were not recognized by any processor: '[androidManifestFile]'
:core:compileRetrolambdaRelease
:core:extractReleaseAnnotations
:core:mergeReleaseProguardFiles UP-TO-DATE"

**Comment by WonderCsabo** [comment] 2015-05-29 08:57
Please provide more detail about the issue. This happened after you upgraded to AppCompat 22.2?

**Comment by dodgex** [comment] 2015-05-29 08:59
just as note: for me 22.2.0 works with AA 3.3.1. i only had to add some proguard -dontwarn for my release build

**Comment by WonderCsabo** [comment] 2015-05-29 09:03
This issue is getting really confusing, and i still lack basic information. Please guys provide as much details as possible, according to our [issue guide](https://github.com/excilys/androidannotations/wiki/HowToWriteAnIssue). A repro project would be the most help.

**Comment by matsujun** [comment] 2015-05-29 09:57
If I don't use support.v4.app.DialogFragment on my project, there are no error.
If I use support.v4.app.DialogFragment on my project, there is above error.
(Even if I use @EFragment for my fragment.)

**Comment by matsujun** [comment] 2015-05-29 10:17
I made small sample
https://github.com/matsujun/AAIssue

I just created template app with AndroidStudio, 
applied EActivity to MyActivity,
and made meaningless MyDialogFragment extends support.v4.app.DialogFragment.

**Comment by WonderCsabo** [comment] 2015-05-29 10:19
Thanks, great! I will look at it soon.

**Comment by WonderCsabo** [comment] 2015-05-29 12:21
I suspect what is the problem. There is an inner annotation in the `DialogFragment` class, `@DialogFragment.DialogStyle`. This annotation is used only at one place, in the `DialogFragment.setStyle(@DialogStyle int style, @StyleRes int theme)` method.

The problem happens in `ModelExtractor.extractAncestorsAnnotations`. This method is used to collect all annotations which are found on the parent classes of the actual "root" classes. When we reach `MyDialogFragment`, we iterate over its parents, then we hit `DialogFragment`. We iterate over all enclosed elements (inner classes, methods, fields, etc) in that class, so we find `DialogFragment.setStyle`. And this is where the problem occurs. The retention policy of `@DialogFragment.DialogStyle` is `SOURCE`. So the annotation usage is found, but its class file cannot be loaded, and we fail...

This annotation was added in support lib version `20.0.0`.

**Comment by WonderCsabo** [comment] 2015-05-29 12:34
A little correction: the retention policy was always `SOURCE`. Interestingly, the support lib still contained the .class file for `@DialogFragment.DialogStyle`, that is why AA worked. Since support lib version `22.2`, this .class file is no longer present in the AAR (which is correct according to its retention). I do not know why it was present despite its source-only retention in earlier versions, but that was our luck.

**Comment by WonderCsabo** [comment] 2015-05-29 12:57
I investigated a little bit further. It seems Google is using a bad compiler, or some messed up compiler config. I analyzed the .class file for `DialogFragment` found in the `22.2` support lib with `javap`, and it seems the bytecode still has references for the `@DialogFragment.DialogStyle` annotation, despite it does not exist at all...

I quickly created a small test:

```java
@Retention(RetentionPolicy.SOURCE)
public @interface MyInterface {

}

public class MyClass {
	@MyInterface
	public void hello() { }
}
```

I compiled it, and `MyClass` does not have a reference for the annotation in the .class file (as expected). Also adding this to the project and subclassing `MyClass` then running AA works fine.

So i guess a bug report should be created against the Android Support Library.

**Comment by WonderCsabo** [comment] 2015-05-29 13:36
OK, actually my solution worked because i had `MyClass$MyInterface.class` in may jar. Deleting that reproduces the same issue. So i guess that file should be present, that is while it created in the first place. I do knot why Google deleted it.

**Comment by WonderCsabo** [comment] 2015-05-29 14:58
OK, it seems that the .class file [should be](http://stackoverflow.com/a/30532157/747412) in the support lib jar.

I reported the problem in the Android [bug tracker](http://b.android.com/175086).

Until it is fixed, we can work around the problem when extracting annotations:

* skip `DialogFragment` when walking the ancestor classes, or
* skip all classes of the `android` package.

Maybe the second option is better, since we do not hardwire the particular class, and also will gain performance. However it can cause problems if a client uses a package name starting with `android.`, but i think nobody should do that.

**Comment by BukT0p** [comment] 2015-05-29 15:32
It seems that there are a lot things missing there see https://code.google.com/p/android/issues/detail?id=175083

**Comment by WonderCsabo** [comment] 2015-05-29 15:46
Thanks! Indeed, the listed classes in that issue are similar annotations like `DialogStyle`.

**Comment by AlexanderThiele** [comment] 2015-06-02 07:33
Hey @WonderCsabo , will there be a fix in the near future? or is there a hotfix available?

**Comment by WonderCsabo** [comment] 2015-06-02 08:32
@AlexanderThiele i am not sure we should handle this AA-side. This support lib bug effect lots of libraries (like AA and dagger), and tools (like ProGuard). I think we should wait for Google to fix the root cause instead of applying workarounds in each downstream projects.

Can't you just use the older version of the support lib while it is fixed?

**Comment by jclemus91** [comment] 2015-06-03 15:10
While the error is corrected, in my case, I did downgrade 
*"Android Support Repository rev. 15"* to *14* and
*"Android Support Library rev. 22.2"* to *22.1.1*, both in Extras folder.
It works for me.

**Comment by WonderCsabo** [comment] 2015-06-03 15:13
Yeah, that obviously works, because this problem was introduced in version
22. However you do not have to downgrade in the Sdk manager, only change
the dependency version in your build script (I am assuming you are using
proper dependency management and not just copying the jar).

**Comment by jclemus91** [comment] 2015-06-03 15:36
Hahaha I didn't copy jar, but, it's true, I had to just change the dependency (:

**Comment by AlexanderThiele** [comment] 2015-06-03 17:50
For all who wants to use the new design library with AA. (works for me and only tested the new FAB)

    compile 'com.android.support:support-v4:22.1.1'
    compile 'com.android.support:appcompat-v7:22.1.1'
    compile 'com.android.support:recyclerview-v7:22.1.1'
    compile ('com.android.support:design:22.2.0'){
        exclude module: 'support-v4'
        exclude module: 'appcompat-v7'
    }

**Comment by WonderCsabo** [comment] 2015-06-17 09:00
I am closing this issue, since this will be fixed on Google's side. Until then, use an older version or use some of the workarounds.

**Comment by mazoni** [comment] 2015-06-18 15:33
That's a really odd issue. I'm still using all the 22.1.1 in my build but I'm having the same error after the last sdk manager update, event without updating the build.gradle... I've tried all the mentioned work arounds and nothing works.

**Comment by WonderCsabo** [comment] 2015-06-18 15:34
Are you sure you are using `22.1.1`? Run `gradlew dependencies` and check the result.

**Comment by mazoni** [comment] 2015-06-18 16:41
this is the result of the gradlew dependencies:

+--- com.android.support:support-v4:22.1.0 -> 22.2.0 (*)
+--- com.android.support:appcompat-v7:22.1.0
|    \--- com.android.support:support-v4:22.1.0 -> 22.2.0 (*)
+--- com.android.support:recyclerview-v7:22.1.0
|    +--- com.android.support:support-v4:22.1.0 -> 22.2.0 (*)
|    \--- com.android.support:support-annotations:22.1.0 -> 22.2.0
+--- com.android.support:gridlayout-v7:22.1.0
|    \--- com.android.support:support-v4:22.1.0 -> 22.2.0 (*)


    compile 'com.android.support:support-v4:22.1.0'
    compile 'com.android.support:appcompat-v7:22.1.0'
    compile 'com.android.support:recyclerview-v7:22.1.0'
    compile 'com.android.support:gridlayout-v7:22.1.0'

I'm not really sure what that arrow mean. If it somehow means that it's automatically changing to 22.2.0, how do I force to use the one I've configured?
Thanks a lot for the help so far WonderCsabo

**Comment by WonderCsabo** [comment] 2015-06-18 16:44
One of your dependencies requires 22.2.0, that is why those versions are incremented. Please post your whole `dependencies` block so we can figure it out, or the whole result of that command (or better: both).

**Comment by mazoni** [comment] 2015-06-18 17:15
With a lot of help from @WonderCsabo I've figured out what my problem was. It turns out one of the libraries I was using ('com.rockerhieu.emojicon:library:1.0') was using the dependency to support-v4 like this: com.android.support:support-v4:+ ... and that forced all other dependencies to use 22.2.0 instead of 22.1.0. Once again thanks a lot for your help, let me know if I can contribute anymore to make this issue clearer.

**Comment by WonderCsabo** [comment] 2015-06-18 17:19
Cool. This case also shows why it is a very bad idea to use + in a version number. But did you manage to solve the issue? You should use something like this:
```groovy
compile ('com.rockerhieu.emojicon:library:1.0'){
    exclude module: 'support-v4'
}
```

**Comment by mazoni** [comment] 2015-06-18 17:23
Exactly, this is my working dependencies block:
```groovy
dependencies {
    apt 'org.androidannotations:androidannotations:3.2'
    compile 'org.springframework.android:spring-android-rest-template:1.0.1.RELEASE'
    compile group: 'com.google.guava', name: 'guava', version: '11.0.2'
    compile 'com.facebook.android:facebook-android-sdk:4.1.0'
    compile 'org.codehaus.jackson:jackson-jaxrs:1.9.13'
    compile 'javax.ws.rs:javax.ws.rs-api:2.0-m01'
    compile 'org.androidannotations:androidannotations-api:3.2'
    compile 'com.android.support:multidex:1.0.0'
    compile 'com.android.support:support-v4:22.1.1'
    compile 'com.android.support:appcompat-v7:22.1.1'
    compile 'com.android.support:recyclerview-v7:22.1.1'
    compile 'com.android.support:gridlayout-v7:22.1.1'
    compile 'de.greenrobot:greendao:1.3.7'
    compile 'com.makeramen:roundedimageview:1.5.0'
    compile 'com.squareup.picasso:picasso:2.4.0'
    compile 'com.kbeanie:image-chooser-library:1.4.02@aar'
    compile 'com.github.chrisbanes.photoview:library:1.2.3'
    compile 'com.github.carlonzo.stikkyheader:core:0.0.2-SNAPSHOT'
    compile ('com.rockerhieu.emojicon:library:1.0') {
        exclude group: 'com.android.support', module:'support-v4'
    }
    compile 'com.roomorama:caldroid:2.0.0'
    compile('com.crashlytics.sdk.android:crashlytics:2.2.4@aar') {
        transitive = true
    }
    compile ('io.intercom.android:intercom-sdk:1.0.0@aar') {
        transitive = true
    }

}
```

**Comment by WonderCsabo** [comment] 2015-06-18 17:34
Great! Tip: `transitive = true` is unnecessary, you should use consistent lines (not `compile group:`), and finally, the latest AA version is 3.3.1. :wink:

**Comment by rivancic** [comment] 2015-06-22 16:33
Hey, 
I bumped on the same problem today, when I imported new android design support library which needs new 22.2 versions of support libraries. And to downgrade to the 21.1.1 was a no go solution for me, because then I couldn't use the functionality form design support library.
The only solution for me was to manually add the support-v4 library to the /libs directory like explained on link https://code.google.com/p/android/issues/detail?id=175086 answer from #9 koen.vla...@gmail.com 
> as that file (android-support-v4.jar) does seem to have DialogFragment$DialogStyle.

and exclude the v4 dependencies from the com.android.support:design:22.2.0

grade file now looks like:
```
def AAVersion = '3.3.1'
dependencies {     
compile project(':core')     
apt "org.androidannotations:androidannotations:$AAVersion"     
compile "org.androidannotations:androidannotations-api:$AAVersion"    
compile files('libs/android-support-v4.jar')     
compile('com.android.support:design:22.2.0') {         
    exclude module: 'support-v4'         
} 
```

Thanks for helping me finding the temporary solution.

**Comment by WonderCsabo** [comment] 2015-06-22 16:52
@rivancic great. However i really do not like adding jars to source control. We could improve that solution with the help of the [maven-android-sdk-deployer](https://github.com/simpligility/maven-android-sdk-deployer), deploy the jar into the local maven repository, and depend on it:
```sh
git clone git@github.com:simpligility/maven-android-sdk-deployer.git
cd maven-android-sdk-deployer/extras/compatibility-v4
mvn install
```

```groovy
repositories {
  mavenLocal()
  // ...
}

dependencies {
  // ...
  compile 'android.support:compatibility-v4:22.2.0' // instead of compile files('libs/...') 
}

**Comment by easyspeak** [comment] 2015-06-24 22:23
@WonderCsabo @rivancic  I needed the latest mediarouter-v7 for a CastCompanionLibrary-android update. I tried your local android-support-v4.jar but it caused conflicts with android support annotations. After a lot of frustration I found this solution that removes the need for a local jar.

```groovy
    // Force stable version of support-v4 and appcompat-7
    // This handles includes from all other gradle dependencies
    compile ('com.android.support:support-v4:22.0.0') {
        force = true
    }
    compile ('com.android.support:appcompat-v7:22.0.0') {
        force = true
    }
   // Include other support dependencies @22.2.0 as needed
    compile 'com.android.support:recyclerview-v7:22.2.0'
    compile 'com.android.support:mediarouter-v7:22.2.0'
```

**Comment by WonderCsabo** [comment] 2015-06-24 22:24
I do not know the `force` command. What does it do exactly?

**Comment by easyspeak** [comment] 2015-06-25 00:17
I was not aware of it either until today but I guess it forces a dependency to be locked at the given version.

**Comment by WonderCsabo** [comment] 2015-06-25 00:24
Thanks! It seems the feature is documented here
https://docs.gradle.org/2.4/dsl/org.gradle.api.artifacts.dsl.DependencyHandler.html

**Comment by danpe** [comment] 2015-07-07 20:08
:+1: 
The patches aren't so good..
You think there will be a fix from google side?

**Comment by bperin** [comment] 2015-07-07 21:26
@easyspeak AWESOME FIND! This worked for me too. This bug was so obnoxious, I really needed to use the design support libs but none of the other fixes seemed to do the trick

**Comment by WonderCsabo** [comment] 2015-07-07 21:30
@danpe there will be for sure, but nobody knows when.

**Comment by danpe** [comment] 2015-07-08 08:12
Why is this a Google Bug though ? the support library v4 works without androidannotations

**Comment by WonderCsabo** [comment] 2015-07-08 08:30
@danpe i already explained here (see this https://github.com/excilys/androidannotations/issues/1435#issuecomment-106787659 and down), and i also [reported](http://b.android.com/175086) this to Google, they confirmed this is a bug. Luckily the bug does not effects "normal" builds, but causes troubles with annotation processors which are scanning the classes, like AndroidAnnotations and [Dagger](https://github.com/google/dagger/issues/197).
But we can create a workaround at AA side. If i would have know Google is not fixing this too soon, maybe i would have already create that workaround.

**Comment by WonderCsabo** [comment] 2015-07-09 18:30
Since Google is still not reacting, we are adding a workaround for this into AndroidAnnotations.

**Comment by WonderCsabo** [comment] 2015-07-10 07:17
We just released [**AndroidAnnotations 3.3.2**](http://www.google.com/url?q=http%3A%2F%2Fsearch.maven.org%2F%23search%257Cga%257C1%257Cg%253A%2522org.androidannotations%2522%EF%BB%BF&sa=D&sntz=1&usg=AFQjCNGfSxJ7d1AHUT91SWyIHWFDc8bwbA), which addresses this issue. Update to it, and you no longer have to use workarounds in *build.gradle* with Support Library 22.2.0.

**Closed by WonderCsabo** 2015-07-10 07:17 UTC
Labels: Enhancement

**Comment by easyspeak** [comment] 2015-07-10 18:22
@WonderCsabo Thank you for the fix. The previous workaround failed on emulators and some older Motorola and Samsung devices. You just saved my automated tests and my sanity.

**Comment by dodgex** [comment] 2015-07-18 08:30
support lib 22.2.1 has been released. according to [this comment](https://code.google.com/p/android/issues/detail?id=175086#c42) it seems that the issue has been fixed

**Comment by WonderCsabo** [comment] 2015-07-18 08:35
Indeed, i can verify it. However AA 3.3.2 already fixed this problem from our side. :)

**Comment by dodgex** [comment] 2015-07-18 08:38
yeah, i just wanted to mention it here :)

**Comment by WonderCsabo** [comment] 2015-07-18 08:40
Thanks for doing that! You are right, it was worth mentioning, because
other libraries still suffered from this bug.
