### ISSUE TITLE
4.0-SNAPSHOT

### ISSUE THREAD

**Issue by noinnion** [excilys/androidannotations#1594] opened 2015-10-16 09:24 UTC
Hi, I tried to use 4.0-SNAPSHOT but it does not work.

Here are my settings in app.gradle:

    repositories {
        maven { url 'https://oss.sonatype.org/content/repositories/snapshots' }
    }

    def AAVersion = "4.0-SNAPHOT"

    dependencies {
        apt "org.androidannotations:androidannotations:$AAVersion"
        compile "org.androidannotations:androidannotations-api:$AAVersion"
    }

I get following error:

`Error:Could not find org.androidannotations:androidannotations:4.0-SNAPHOT.
Searched in the following locations:
    https://jcenter.bintray.com/org/androidannotations/androidannotations/4.0-SNAPHOT/androidannotations-4.0-SNAPHOT.pom
    https://jcenter.bintray.com/org/androidannotations/androidannotations/4.0-SNAPHOT/androidannotations-4.0-SNAPHOT.jar
    https://raw.github.com/Raizlabs/maven-releases/master/releases/org/androidannotations/androidannotations/4.0-SNAPHOT/androidannotations-4.0-SNAPHOT.pom
    https://raw.github.com/Raizlabs/maven-releases/master/releases/org/androidannotations/androidannotations/4.0-SNAPHOT/androidannotations-4.0-SNAPHOT.jar
    https://oss.sonatype.org/content/repositories/snapshots/org/androidannotations/androidannotations/4.0-SNAPHOT/androidannotations-4.0-SNAPHOT.pom
    https://oss.sonatype.org/content/repositories/snapshots/org/androidannotations/androidannotations/4.0-SNAPHOT/androidannotations-4.0-SNAPHOT.jar
    https://nexus.kupferwerk.net/content/groups/public/org/androidannotations/androidannotations/4.0-SNAPHOT/androidannotations-4.0-SNAPHOT.pom
    https://nexus.kupferwerk.net/content/groups/public/org/androidannotations/androidannotations/4.0-SNAPHOT/androidannotations-4.0-SNAPHOT.jar
    https://maven.fabric.io/public/org/androidannotations/androidannotations/4.0-SNAPHOT/androidannotations-4.0-SNAPHOT.pom
    https://maven.fabric.io/public/org/androidannotations/androidannotations/4.0-SNAPHOT/androidannotations-4.0-SNAPHOT.jar
    file:/Users/hle/Library/Android/sdk/extras/android/m2repository/org/androidannotations/androidannotations/4.0-SNAPHOT/androidannotations-4.0-SNAPHOT.pom
    file:/Users/hle/Library/Android/sdk/extras/android/m2repository/org/androidannotations/androidannotations/4.0-SNAPHOT/androidannotations-4.0-SNAPHOT.jar
    file:/Users/hle/Library/Android/sdk/extras/google/m2repository/org/androidannotations/androidannotations/4.0-SNAPHOT/androidannotations-4.0-SNAPHOT.pom
    file:/Users/hle/Library/Android/sdk/extras/google/m2repository/org/androidannotations/androidannotations/4.0-SNAPHOT/androidannotations-4.0-SNAPHOT.jar
Required by:
    android-app:app:unspecified`

**Comment by dodgex** [comment] 2015-10-16 09:26
`def AAVersion = "4.0-SNAPHOT"`
should be
`def AAVersion = "4.0-SNAPSHOT"`
you are missing an `S`

**Comment by WonderCsabo** [comment] 2015-10-16 09:26
You should be a little bit more careful. You made a typo in `SNAPSHOT`. :smirk:

**Comment by noinnion** [comment] 2015-10-16 09:31
oh right, how could I missed it?
Thanks a lot.

Now I change it to 4.0-SNAPSHOT
I get following error in gradle

Error:Execution failed for task ':app:compileDebugJavaWithJavac'.
> java.lang.ClassCastException: com.sun.tools.javac.code.Symbol$MethodSymbol cannot be cast to javax.lang.model.element.TypeElement
dle's dependency cache may be corrupt (this sometimes occurs after a network connection timeout.)
<a href="syncProject">Re-download dependencies and sync project (requires network)</a></li><li>The state of a Gradle build process (daemon) may be corrupt. Stopping all Gradle daemons may solve this problem.
<a href="stopGradleDaemons">Stop Gradle build processes (requires restart)</a></li><li>Your project may be using a third-party plugin which is not compatible with the other plugins in the project or the version of Gradle requested by the project.</li></ul>In the case of corrupt Gradle processes, you can also try closing the IDE and then killing all Java processes.
```

**Comment by WonderCsabo** [comment] 2015-10-16 09:33
Please run with Gradle with `--stacktrace` and paste it.

**Comment by noinnion** [comment] 2015-10-16 09:42
Exception is: 

org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app:compileDebugJavaWithJavac'.
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
	at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:64)
	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:42)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
	at org.gradle.api.internal.AbstractTask.executeWithoutThrowingTaskFailure(AbstractTask.java:310)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.executeTask(AbstractTaskPlanExecutor.java:79)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:63)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:51)
	at org.gradle.execution.taskgraph.ParallelTaskPlanExecutor.process(ParallelTaskPlanExecutor.java:45)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(DefaultTaskGraphExecuter.java:88)
	at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:37)
	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:62)
	at org.gradle.execution.DefaultBuildExecuter.access$200(DefaultBuildExecuter.java:23)
	at org.gradle.execution.DefaultBuildExecuter$2.proceed(DefaultBuildExecuter.java:68)
	at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:32)
	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:62)
	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:55)
	at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:149)
	at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:106)
	at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:86)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:90)
	at org.gradle.tooling.internal.provider.runner.BuildModelActionRunner.run(BuildModelActionRunner.java:54)
	at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:41)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:28)
	at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:49)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:37)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:26)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.RequestStopIfSingleUsedDaemon.execute(RequestStopIfSingleUsedDaemon.java:34)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:74)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:72)
	at org.gradle.util.Swapper.swap(Swapper.java:38)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:72)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.health.DaemonHealthTracker.execute(DaemonHealthTracker.java:47)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:66)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:71)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.health.HintGCAfterBuild.execute(HintGCAfterBuild.java:41)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:50)
	at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:246)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
	at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
Caused by: java.lang.RuntimeException: java.lang.ClassCastException: com.sun.tools.javac.code.Symbol$VarSymbol cannot be cast to javax.lang.model.element.TypeElement
	at com.sun.tools.javac.main.Main.compile(Main.java:469)
	at com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:132)
	at org.gradle.api.internal.tasks.compile.JdkJavaCompiler.execute(JdkJavaCompiler.java:45)
	at org.gradle.api.internal.tasks.compile.JdkJavaCompiler.execute(JdkJavaCompiler.java:33)
	at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.delegateAndHandleErrors(NormalizingJavaCompiler.java:101)
	at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.execute(NormalizingJavaCompiler.java:50)
	at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.execute(NormalizingJavaCompiler.java:36)
	at org.gradle.api.internal.tasks.compile.CleaningJavaCompilerSupport.execute(CleaningJavaCompilerSupport.java:34)
	at org.gradle.api.internal.tasks.compile.CleaningJavaCompilerSupport.execute(CleaningJavaCompilerSupport.java:25)
	at org.gradle.api.tasks.compile.JavaCompile.performCompilation(JavaCompile.java:157)
	at org.gradle.api.tasks.compile.JavaCompile.compile(JavaCompile.java:137)
	at org.gradle.api.tasks.compile.JavaCompile.compile(JavaCompile.java:91)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:75)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$IncrementalTaskAction.doExecute(AnnotationProcessingTaskFactory.java:243)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:219)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$IncrementalTaskAction.execute(AnnotationProcessingTaskFactory.java:230)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:208)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
	... 57 more
Caused by: java.lang.ClassCastException: com.sun.tools.javac.code.Symbol$VarSymbol cannot be cast to javax.lang.model.element.TypeElement
	at com.raizlabs.android.dbflow.processor.handler.MigrationHandler.onProcessElement(MigrationHandler.java:23)
	at com.raizlabs.android.dbflow.processor.handler.BaseContainerHandler.handle(BaseContainerHandler.java:23)
	at com.raizlabs.android.dbflow.processor.model.ProcessorManager.handle(ProcessorManager.java:278)
	at com.raizlabs.android.dbflow.processor.DBFlowProcessor.process(DBFlowProcessor.java:85)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:793)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:722)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$1700(JavacProcessingEnvironment.java:97)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1029)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1163)
	at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1108)
	at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:824)
	at com.sun.tools.javac.main.Main.compile(Main.java:439)
	... 75 more

**Comment by WonderCsabo** [comment] 2015-10-16 09:45
This error comes from another annotation processor, not AndroidAnnotation. It seems you are using `@com.raizlabs.android.dbflow.annotation.Migration` annotation on a wrong element.

**Comment by WonderCsabo** [comment] 2015-10-16 21:16
I am closing this, because the problem is not related to us.

**Closed by WonderCsabo** 2015-10-16 21:16 UTC

**Comment by WonderCsabo** [comment] 2015-11-26 14:14
Hey guys! @mathieudebrito also experienced a similar problem. In the investigation it turned out the root of the problem was that he was using `@NoTitle`, but that annotation was removed so that created a compile error and in the end resulted in an exception. You should check the annotation usages of AA 4.0 that you are using all annotations correctly. There will be a list of breaking changes of AA 4.0 when it is released.
