### ISSUE TITLE
Androidannotations and multidex  option

### ISSUE THREAD

**Issue by trungptdhcn** [excilys/androidannotations#1303] opened 2015-01-06 01:41 UTC
I use android annotation and mutildex option in my project, I have issue when compile project with maven , some classes use @Bean, @EFragment ... have been duplicate when proccess add to dex file. so Is this issue from using android annotations?

**Comment by dodgex** [comment] 2015-01-06 07:14
can you build a small sample project where the issue occurs that we can use to test?

**Comment by WonderCsabo** [comment] 2015-01-06 12:20
I doubt the issue is coming from us. We just generate a subclass suffixed with _. If we would generate duplicate classes, the build would fail in the very compilation phase.

**Comment by trungptdhcn** [comment] 2015-01-08 01:26
Amazing, after i setup environment for my PC again, my project had run well. I don't know what happen?  But a some PC in my office have this issue

**Comment by WonderCsabo** [comment] 2015-01-08 01:34
Since you provided zero information we cannot tell. However, I still doubt
the issue is at our side. Please post an example project which reproduces
the error.

**Comment by trungptdhcn** [comment] 2015-01-08 03:17
Ok i created small project with mutildex and android annotation.Please help me check issues can happen in my code. this is my project https://github.com/trungptdhcn/mutildex-androidannotation.git

**Comment by WonderCsabo** [comment] 2015-01-08 11:41
@trungptdhcn i have little experience about multidex. I see your project contains a package which generates the main dex list. This is a very bad idea, because these classes and deps will be included in the final APK. That thing should be in a separate project (or it is only for the sake for the simple example? ). I tried to generate the main dex list with android-maven-plugin instead, but i found https://github.com/simpligility/android-maven-plugin/issues/556.
I did not tried to use your [tool](https://github.com/trungptdhcn/mutildex-androidannotation/blob/master/src/main/java/com/trungpt/example/tool/GenerateMultidexKeep.java), as it needs additional instructions. Maybe it generates an invalid .keep file and that's why some classes gets duplicated.

However, it is pretty clear that we are not responsible for this issue at all. We just generate two, completely valid and unique class source file. I suggest to continue the multidex discussion on the android-maven-plugin mailing list or the referenced android-maven-plugin issue. Actually i think i spent too much time investigating an issue which is caused by different projects, this is partially my fault :confused:.

**Closed by WonderCsabo** 2015-01-08 11:41 UTC

**Comment by parmalazs** [comment] 2015-01-08 12:11
https://developer.android.com/tools/building/multidex.html

I use this and AA and I have no problem.

**Comment by WonderCsabo** [comment] 2015-01-08 12:15
What tool do you use to generate the main dex classes list (.keep)?

**Comment by parmalazs** [comment] 2015-01-08 12:19
IDK, this is the official multidex support by google. (It's just works like
a charm.)

**Comment by WonderCsabo** [comment] 2015-01-08 12:20
You are using the gradle build system, i see.
