### ISSUE TITLE
can not use id symbol as the field of Eactivity class. 

### ISSUE THREAD

**Issue by foxundermoon** [excilys/androidannotations#1487] opened 2015-07-07 03:49 UTC
if i use 'id' symbol will  compile error.

**Comment by WonderCsabo** [comment] 2015-07-07 06:02
Please add more information per the [issue guide](https://github.com/excilys/androidannotations/wiki/HowToWriteAnIssue), which is already referenced on the top of the [new issue page](https://github.com/excilys/androidannotations/issues/new). For example your code, AA version, etc.

**Comment by dodgex** [comment] 2015-07-07 06:41
i think it is more or less the same issue as https://github.com/excilys/androidannotations/issues/1323

**Comment by WonderCsabo** [comment] 2015-07-07 08:37
good point @dodgex, but let's wait for @foxundermoon to clarify this issue.

**Comment by WonderCsabo** [comment] 2015-07-09 00:01
I realized I cannot reproduce the problem raised in the referenced issue:https://github.com/excilys/androidannotations/issues/1323#issuecomment-119746379

What is the exact problem here?

**Comment by WonderCsabo** [comment] 2015-07-10 07:31
OK, i managed to reproduce the problem there. I am closing this in favor of #1323. @foxundermoon feel free to reopen, if you think this is not a duplicate. Thanks.

**Closed by WonderCsabo** 2015-07-10 07:31 UTC
