### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by jclemus91** [excilys/androidannotations#1439] opened 2015-06-02 21:17 UTC
Error:(41, 8) error: Something went wrong: Unexpected error in AndroidAnnotations 3.3.1!
You should check if there is already an issue about it on https://github.com/excilys/androidannotations/search?q=com.sun.tools.javac.code.Symbol%24CompletionFailure&type=Issues
If none exists, please open a new one with the following content and tell us if you can reproduce it or not. Don't forget to give us as much information as you can (like parts of your code in failure).
Java version: javac 1.7.0_79
Javac processors options: androidManifestFile=C:\Users\ANDROID\Documents\ArpaTigre\JamesNow\project\JamesNow\app\build\intermediates\manifests\full\debug\AndroidManifest.xml
Stacktrace: com.sun.tools.javac.code.Symbol$CompletionFailure: class file for android.support.v4.app.DialogFragment$DialogStyle not found

**Comment by WonderCsabo** [comment] 2015-06-02 21:21
Thanks for reporting. Although next time please add much more detail (for example your annotated code, [etc](https://github.com/excilys/androidannotations/wiki/HowToWriteAnIssue)). Also, check out whether the issue already reported or not.

This is a duplicate of #1435. Please see that issue for details and possible workarounds.

**Closed by WonderCsabo** 2015-06-02 21:21 UTC

**Comment by jclemus91** [comment] 2015-06-02 21:30
Exactly I don't know, but yesterday I updated my tools to 22. Thats it. Here is the line where is the error.

![error](https://cloud.githubusercontent.com/assets/4140571/7947730/8ed18248-0944-11e5-9333-b22a94dcf980.PNG)

**Comment by WonderCsabo** [comment] 2015-06-02 21:31
Thanks! As i already wrote, lucky for you, i know what is the problem even from this minimal info. :wink: See #1435 for details.

**Comment by jclemus91** [comment] 2015-06-02 21:45
Ok, thanks!
